Fix typo that causes nx graph to crash
I've been having this error when I create an app with Nx 
```
Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it.
  An error occurred while processing files for the @nx/eslint/plugin plugin.
    - apps/blog/.eslintrc.json: Failed to load plugin '@nx/nx' declared in '.eslintrc.json#overrides[0]': Cannot find module '@nx/eslint-plugin-nx'
  Require stack:
  - /Users/ngilyass/projects/confs/findRally/apps/blog/__placeholder__.js
  Referenced from: /Users/ngilyass/projects/confs/findRally/apps/blog/.eslintrc.json
      Error: Failed to load plugin '@nx/nx' declared in '.eslintrc.json#overrides[0]': Cannot find module '@nx/eslint-plugin-nx'
      Require stack:
      - /Users/ngilyass/projects/confs/findRally/apps/blog/__placeholder__.js
      Referenced from: /Users/ngilyass/projects/confs/findRally/apps/blog/.eslintrc.json
          at Module._resolveFilename (node:internal/modules/cjs/loader:1152:15)
          at Function.resolve (node:internal/modules/helpers:190:19)
          at Object.resolve (/Users/ngilyass/projects/confs/findRally/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2346:46)
          at ConfigArrayFactory._loadPlugin (/Users/ngilyass/projects/confs/findRally/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3414:33)
          at ConfigArrayFactory._loadExtendedPluginConfig (/Users/ngilyass/projects/confs/findRally/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3233:29)
          at ConfigArrayFactory._loadExtends (/Users/ngilyass/projects/confs/findRally/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3154:29)
          at ConfigArrayFactory._normalizeObjectConfigDataBody (/Users/ngilyass/projects/confs/findRally/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3095:25)
          at _normalizeObjectConfigDataBody.next (<anonymous>)
          at ConfigArrayFactory._normalizeObjectConfigData (/Users/ngilyass/projects/confs/findRally/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3040:20)
          at _normalizeObjectConfigData.next (<anonymous>)
```

when changed the correct eslint plugin to extends it works